export const mockRoutes = [
  {
    id: 'route_001',
    name: 'The Crimson Beast',
    grade: 'V2',
    wallType: 'Overhang',
    color: '#E74C3C',
    setDate: '2024-01-15',
    description: 'Steep overhang with crimpy holds. Great for power training.',
    holds: 12,
    difficulty: 'intermediate',
  },
  {
    id: 'route_002',
    name: 'Midnight Slab',
    grade: 'V4',
    wallType: 'Slab',
    color: '#2C3E50',
    setDate: '2024-01-20',
    description: 'Technical slab with friction-dependent movement.',
    holds: 18,
    difficulty: 'advanced',
  },
  {
    id: 'route_003',
    name: 'Golden Traverse',
    grade: 'V0',
    wallType: 'Vertical',
    color: '#F39C12',
    setDate: '2024-01-10',
    description: 'Beginner-friendly vertical route, perfect for warm-ups.',
    holds: 8,
    difficulty: 'beginner',
  },
  {
    id: 'route_004',
    name: 'The Emerald Chimney',
    grade: 'V5',
    wallType: 'Chimney',
    color: '#27AE60',
    setDate: '2024-01-25',
    description: 'Challenging chimney route requiring body tension and footwork.',
    holds: 20,
    difficulty: 'expert',
  },
];

export const mockUsers = [
  {
    id: 'user_001',
    name: 'Alex Rivera',
    email: 'alex@example.com',
    joinDate: '2023-06-15',
    experience: 'intermediate',
    maxGrade: 'V3',
    routesCompleted: 24,
    avatar: '👨‍🦱',
  },
  {
    id: 'user_002',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    joinDate: '2023-08-22',
    experience: 'advanced',
    maxGrade: 'V5',
    routesCompleted: 42,
    avatar: '👩‍🦰',
  },
  {
    id: 'user_003',
    name: 'Marcus Johnson',
    email: 'marcus@example.com',
    joinDate: '2023-11-01',
    experience: 'beginner',
    maxGrade: 'V1',
    routesCompleted: 8,
    avatar: '👨‍🦲',
  },
  {
    id: 'user_004',
    name: 'Emma Thompson',
    email: 'emma@example.com',
    joinDate: '2024-01-05',
    experience: 'expert',
    maxGrade: 'V6',
    routesCompleted: 67,
    avatar: '👩‍🦱',
  },
];

export const mockHallInfo = {
  name: 'Boulder Heights Climbing Hall',
  location: 'Downtown',
  established: 2015,
  totalWalls: 8,
  operatingHours: '6 AM - 10 PM',
  contact: '+1-555-0123',
  maxCapacity: 150,
};

export const mockRouteStats = [
  {
    id: 'stat_001',
    routeId: 'route_001',
    userId: 'user_001',
    completed: true,
    time: '12:45',
    date: '2024-01-28',
  },
  {
    id: 'stat_002',
    routeId: 'route_002',
    userId: 'user_002',
    completed: true,
    time: '18:30',
    date: '2024-01-28',
  },
  {
    id: 'stat_003',
    routeId: 'route_003',
    userId: 'user_003',
    completed: true,
    time: '10:15',
    date: '2024-01-27',
  },
  {
    id: 'stat_004',
    routeId: 'route_004',
    userId: 'user_004',
    completed: true,
    time: '19:45',
    date: '2024-01-28',
  },
];
